### ISSUE TITLE
Hangs on macOS Catalina

### ISSUE THREAD

**Issue by aduh95** [h4llow3En/mac-notification-sys#15]
Hey, I've tried to build and run the example code on Catalina, but it seems it is somehow broken. Nothing is displayed on the console, nor the program exits, it just hangs forever and no notification is displayed either.

rustc 1.43.0 (4fb7144ed 2020-04-20)
macOS 10.15.4 (19E287)
mac-notification-sys "0.1.3"

**Comment by h4llow3En** [comment]
Please try latest release at this moment 0.3
