### ISSUE TITLE
Mac OS X 11.0.1 build fails

### ISSUE THREAD

**Issue by ahcm** [h4llow3En/mac-notification-sys#27]
[err.txt](https://github.com/h4llow3En/mac-notification-sys/files/5619778/err.txt)

**Comment by algoz098** [comment]
had similar problem fixed by removing and reinstalling the xcode commandtools.

**Comment by schickling** [comment]
Same problem on macOS 12.

**Comment by schickling** [comment]
@hoodie does closing mean the problem have been addressed in a new release? 🙏

**Comment by hoodie** [comment]
no sorry, I should have written a comment here. I assume that the issue is related missing systems packages being installed
