### ISSUE TITLE
issues with threading. 

### ISSUE THREAD

**Issue by ntrippar** [h4llow3En/mac-notification-sys#4]
Hi if i use threading the calls to sendNotifications hangs.  its because of the while on ncDelegate.keepRunning and problably the osx call. deleting that start working correcly. i suppose that you added that to keep running the app while the deliverNotification send the note. but if the call was already made we should suppose that was already send. also we can use some local variable for that.

**Comment by h4llow3En** [comment]
Currently I am a bit busy and not that firm in objc.
Could you make a PR with those changes? I would be more than happy about it.

**Comment by h4llow3En** [comment]
Yes I added the keep Running to wait until the notification is scheduled correctly. I tried some different things but this was the most promissing

**Comment by ntrippar** [comment]
yeah of course. i did some test and forked the code. but really never finished. i will fix this and make you the PR :)

**Comment by h4llow3En** [comment]
I will try to fix this myself

**Comment by h4llow3En** [comment]
It is at least needed to wait 0.1 Seconds to schedule and/or deliver the notification
