### ISSUE TITLE
Action buttons

### ISSUE THREAD

**Issue by probablykasper** [h4llow3En/mac-notification-sys#47]
I want to show simple reminder notifications which doesn't automatically go away until the user manually dismisses it. To do that, I believe the way to go is to have a `Done` button in the notification

**Comment by nihilok** [comment]
> I want to show simple reminder notifications which doesn't automatically go away until the user manually dismisses it. To do that, I believe the way to go is to have a `Done` button in the notification

You can do this with a single main action button, setting the text to 'Done'. Similar to the example here: https://github.com/h4llow3En/mac-notification-sys/blob/master/examples/actions.rs

Don't use close_button, as that will give you two buttons: AFAICS there will always be a main button and by default it says "Show", so you can change the text and behaviour by adding a MainButton::SingleAction option.

**Comment by probablykasper** [comment]
You're absolutely right, thank you!

For actually making the notifications not go away, it seems to be impossible without the user specifying it: https://stackoverflow.com/questions/69782010/is-it-possible-to-set-default-alert-style-for-macos-unnotification#comment127829528_69782010
