### ISSUE TITLE
Version 0.6.2 breaks notify-rust

### ISSUE THREAD

**Issue by girardof** [h4llow3En/mac-notification-sys#59]
Hi everyone, I encountered the following issue recently: 

When using `notify-rust = "4.11.3"` in my cargo file I get the following error at compilation time: 

```
error[E0308]: mismatched types
  --> .cargo/registry/src/index.crates.io-6f17d22bba15001f/mac-notification-sys-0.6.2/build.rs:24:19
   |
24 |             .flag(format!("-mmacos-version-min={}", min_version))
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
```

Using the same cargo file the error is gone when I force `mac-notification-sys` to use the version 0.6.1: 

`cargo update -p mac-notification-sys --precise 0.6.1`

I think the issue might have been introduced by the latest commit: https://github.com/h4llow3En/mac-notification-sys/commit/611a9176998bb28bf2f8be8be3922c5ac9c0baed 

The issue is not only related to mac-notification-sys but I can see that some maintainer work on notify-rust as well so I figured the compatibility between the two libraries is something that matters.

**Comment by hoodie** [comment]
Thanks for bringing this up. I'm slightly confused, as this was actually supposed to fix an issue that was reported at the time. I think [cc had changed their api which had led to a clippy warning](https://github.com/rust-lang/cc-rs/commit/a1e291a4f5bb7ef7f75bb6606ad2149827721946). 
I personally cannot yet reproduce this now, but for me either version seems to work, so I'd be happy to roll this back.

Just to help me understand, what version of [`cc`](https://lib.rs/crates/cc) do you have in your `Cargo.lock`?

**Comment by girardof** [comment]
I'm sorry I might have open this issue a little bit too quickly, for some reason I can't reproduce the issue anymore. I tried many thing in the weekend to fix it so maybe the version of cc I was using was too old but I can't say for sure.

Anyway thank you for your response and sorry for the inconvenience.

**Comment by hoodie** [comment]
No worries at all. Thanks for reporting in.
