### ISSUE TITLE
MAC OS 14.5 build error

### ISSUE THREAD

**Issue by Sunnnner** [h4llow3En/mac-notification-sys#60]
rust version: rustc 1.79.0 (129f3b996 2024-06-10)
error details: 
![image](https://github.com/user-attachments/assets/1de4f74d-1a5d-45be-b8bc-0faec294b079)

**Comment by Sunnnner** [comment]
https://github.com/h4llow3En/mac-notification-sys/pull/61

**Comment by hoodie** [comment]
I'm a bit surprised about the sudden Spike and occurrences of this issue.
